version: "3.5"

services:
  roach1:
    image: cockroachdb/cockroach:v22.1.8
    hostname: roach1
    container_name: roach1
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start --insecure --join=roach1,roach2,roach3
    volumes:
      - "roach1:/cockroach/cockroach-data"
  roach2:
    image: cockroachdb/cockroach:v22.1.8
    hostname: roach2
    container_name: roach2
    command: start --insecure --join=roach1,roach2,roach3
    volumes:
      - "roach2:/cockroach/cockroach-data"
  roach3:
      image: cockroachdb/cockroach:v22.1.8
      hostname: roach3
      container_name: roach3
      command: start --insecure --join=roach1,roach2,roach3
      volumes:
        - "roach3:/cockroach/cockroach-data"

volumes:
  roach1:
    driver: local
  roach2:
    driver: local
  roach3:
    driver: local